language: php
sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - '7.0'
  - '7.1'
  - nightly

env:
  - SYMFONY_VERSION="3.0.*" DB=mysql

before-install:
  - composer self-update

install:
  - cp app/config/notification.yml.dist app/config/notification.yml
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - composer install

script:
  - ./vendor/bin/simple-phpunit
