language: php
sudo: false

services:
  - redis-server

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - '7.0'
  - '7.1'
  - nightly
  - hhvm

matrix:
    allow_failures:
        - php: hhvm
        - php: nightly

env:
  - SYMFONY_VERSION="3.0.*" DB=mysql

before-install:
  - composer self-update

install:
  - cp app/config/notification.yml.dist app/config/notification.yml
  - composer install

script:
  - ./vendor/bin/simple-phpunit --coverage-text
