FROM wolnosciowiec/docker-php-app:arm7hf

ENV APP_ENV "prod"
ENV DATABASE_URL "sqlite:///%kernel.project_dir%/var/data.db"

ADD . /var/www/html

RUN [ "cross-build-start" ]
RUN cd /var/www/html \
    && cp ./app/config/parameters.yml.cloud.dist ./app/config/parameters.yml \
    && cp ./app/config/notification.yml.dist ./app/config/notification.yml \
    && chown www-data:www-data ./ -R \
    && make deploy
RUN [ "cross-build-end" ]
