imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

parameters:
    locale: en

framework:
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    fragments:       ~
    http_method_override: true
    php_errors:
        log: true

swiftmailer:
    transport:            '%mailer_transport%'
    username:             '%mailer_user%'
    password:             '%mailer_password%'
    host:                 '%mailer_host%'
    port:                 false
    encryption:           ~
    auth_mode:            ~
    spool:
        type:                 file
        path:                 '%kernel.cache_dir%/swiftmailer/spool'
    sender_address:       ~
    antiflood:
        threshold:            99
        sleep:                0
    delivery_addresses:   []
    disable_delivery:     ~
    logging:              '%kernel.debug%'

doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        path:     "%database_path%"
        charset:  UTF8

    orm:
        default_entity_manager:  ~
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true


        mappings:
            NotificationBundle:
                type: yml
                prefix: NotificationBundle
                dir: Resources/config/doctrine
                alias: NotificationBundle

jms_serializer:
    handlers:
        datetime:
            default_format: "Y-m-d H:i:s"
            default_timezone: "UTC"

    visitors:
        json:
            options: JSON_PRETTY_PRINT

    metadata:
        debug: true
        auto_detection: true
        directories:
            NotificationBundle:
                namespace_prefix: NotificationBundle
                path: "@NotificationBundle/Resources/config/Serializer"
