notification:
    queue: "notificationbundle.queue.null"
    queue_parameters:
        test_parameter: "test value"
        second_parameter: 123

    allowed_entities:
        Message: "NotificationBundle\\Model\\Entity\\Message\\Message"
        FailureNotification: "NotificationBundle\\Model\\Entity\\Message\\FailureMailMessage"

    enabled_messengers:
        null_messenger:
            service_id: notificationbundle.messenger.null
            class: NotificationBundle\Messenger\NullMessenger
            groups:
                - admin_alert
                - example_1
            config: []
