NotificationBundle\Model\Entity\Message:
    exclusion_policy: ALL
    properties:
        content:
            type: string
            expose: true
        id:
            type: string
            expose: true
        groupName:
            type: string
            expose: true
        couldBeTruncated:
            type: boolean
            expose: true