NotificationBundle\Model\Entity\Message\MailMessage:
    exclusion_policy: none
    properties:
        subject:
            type: string

        from:
            type: string

        recipients:
            type: array
