NotificationBundle\Model\Entity\Message:
    exclusion_policy: none
    properties:
        content:
            type: string

        id:
            type: string

        groupName:
            type: string

        couldBeTruncated:
            type: boolean
            expose: true

        title:
            type: string
