services:
    # Factories
    notificationbundle.factory.messenger:
        class: NotificationBundle\Factory\Messenger\MessengerFactory

    notificationbundle.factory.queue:
        class: NotificationBundle\Factory\Queue\QueueFactory

    notificationbundle.factory.message:
        class: NotificationBundle\Factory\Message\MessageFactory
        arguments:
            serializer: "@serializer"
            logger:     "@logger"

    # Queues
    notificationbundle.queue.redis:
        class: NotificationBundle\Queue\RedisQueue
        arguments:
            configurationProvider: "@notificationbundle.services.configuration.queue"
            serializer: "@serializer"
            logger: "@logger"

    notificationbundle.queue.null:
        class: NotificationBundle\Queue\NullQueue


    # Messengers
    notificationbundle.messenger.twitter:
        class: NotificationBundle\Messenger\TwitterMessenger
        arguments:
            logger:                "@logger"

    notificationbundle.messenger.facebook:
        class: NotificationBundle\Messenger\FacebookFanPageMessenger

    notificationbundle.messenger.email:
        class: NotificationBundle\Messenger\EmailMessenger
        arguments:
            mailer: "@swiftmailer.mailer"
            twig: "@twig"
            logger: "@logger"

    notificationbundle.messenger.slack:
        class: NotificationBundle\Messenger\SlackMessenger
        arguments:
            logger: "@logger"

    notificationbundle.messenger.null:
        class: NotificationBundle\Messenger\NullMessenger

    # Validators
    notificationbundle.validator.message:
        class: NotificationBundle\Controller\Validator\NewMessageValidator
        arguments:
            factory: "@notificationbundle.factory.message"
            logger:  "@logger"
            validator: "@validator"

    # Services
    notificationbundle.services.sender:
        class: NotificationBundle\Services\MessageSenderService
        arguments:
            factory: "@notificationbundle.factory.messenger"
            logger: "@logger"

    notificationbundle.services.configuration.queue:
        class: NotificationBundle\Services\ConfigurationProvider\QueueConfigurationProvider

    notificationbundle.services.cleaner.queue:
        class: NotificationBundle\Services\QueueCleanerService
        arguments:
            factory: "@notificationbundle.factory.queue"
            logger: "@logger"

    notificationbundle.services.processor.queue:
        class: NotificationBundle\Services\Processor\QueueProcessor
        arguments:
            sender: "@notificationbundle.services.sender"
            cleaner: "@notificationbundle.services.cleaner.queue"
            factory: "@notificationbundle.factory.queue"


    # Security
    notificationbundle.security.token_authenticator:
        class: NotificationBundle\Security\TokenAuthenticator

    notificationbundle.security.user_provider:
        class: NotificationBundle\Security\UserProvider
        arguments:
            em: "@doctrine.orm.entity_manager"